import { createElement } from "react";
import {
  AdaptiveOverlayShowcase,
  CommandWorkbenchShowcase,
  DataTableShowcase,
  DiffShowcase,
  FormWorkflowShowcase,
  InspectorGridShowcase,
  LogViewerShowcase,
  ProcessTableShowcase,
  RuntimePlanShowcase,
  SequenceRackShowcase,
  SurfaceCompositionShowcase,
  TerminalShowcase,
  ThemingShowcase,
  TraceTopologyShowcase,
} from "./featureShowcaseScenes";

export const featureShowcases = [
  {
    id: "surface-composition",
    title: "Composable Surfaces",
    description: "Cards, modal-like surfaces, and aspect-ratio frames host full React content and richer workflows.",
    renderDashboard: () => createElement(SurfaceCompositionShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(SurfaceCompositionShowcase, { mode: "components" }),
  },
  {
    id: "adaptive-overlays",
    title: "Adaptive Overlays",
    description: "Tooltip, hover card, and popover now auto-size around React content and preserve composed trigger props.",
    renderDashboard: () => createElement(AdaptiveOverlayShowcase),
    renderComponents: () => createElement(AdaptiveOverlayShowcase),
  },
  {
    id: "form",
    title: "AsciiForm",
    description: "Sectioned forms now support notices, summaries, action bars, and structured rollout workflows.",
    renderDashboard: () => createElement(FormWorkflowShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(FormWorkflowShowcase, { mode: "components" }),
  },
  {
    id: "terminal",
    title: "AsciiTerminal",
    description: "Terminal sessions can now blend live stream lines with command history, search, and filtered views.",
    renderDashboard: () => createElement(TerminalShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(TerminalShowcase, { mode: "components" }),
  },
  {
    id: "log-viewer",
    title: "AsciiLogViewer",
    description: "Live logs now support toolbar content, search filtering, bookmarks, copy actions, and follow control.",
    renderDashboard: () => createElement(LogViewerShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(LogViewerShowcase, { mode: "components" }),
  },
  {
    id: "command-workbench",
    title: "AsciiCommandPalette + AsciiSplitPane",
    description: "Grouped commands now learn recent actions, and split workbenches compose side-by-side task views.",
    renderDashboard: () => createElement(CommandWorkbenchShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(CommandWorkbenchShowcase, { mode: "components" }),
  },
  {
    id: "data-table",
    title: "AsciiDataTable",
    description: "Data tables now support row selection, keyboard navigation, pinned columns, resize controls, and loading/error states.",
    renderDashboard: () => createElement(DataTableShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(DataTableShowcase, { mode: "components" }),
  },
  {
    id: "diff",
    title: "AsciiDiff",
    description: "Diffs can search within content and collapse long unchanged regions.",
    renderDashboard: () => createElement(DiffShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(DiffShowcase, { mode: "components" }),
  },
  {
    id: "process-table",
    title: "AsciiProcessTable",
    description: "Process monitors gained query filtering, sortable summaries, and toolbar composition.",
    renderDashboard: () => createElement(ProcessTableShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(ProcessTableShowcase, { mode: "components" }),
  },
  {
    id: "inspector-grid",
    title: "AsciiInspector + AsciiStatusGrid",
    description: "New domain components for inspection panels and dense operational status boards.",
    renderDashboard: () => createElement(InspectorGridShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(InspectorGridShowcase, { mode: "components" }),
  },
  {
    id: "trace-topology",
    title: "AsciiTraceTimeline + AsciiDependencyGraph",
    description: "New observability views for trace spans and service topology relationships.",
    renderDashboard: () => createElement(TraceTopologyShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(TraceTopologyShowcase, { mode: "components" }),
  },
  {
    id: "sequence-rack",
    title: "AsciiSequenceDiagram + AsciiRackMap",
    description: "New infrastructure views for request choreography and dense rack-level status mapping.",
    renderDashboard: () => createElement(SequenceRackShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(SequenceRackShowcase, { mode: "components" }),
  },
  {
    id: "runtime-plan",
    title: "AsciiFlameGraph + AsciiQueryPlan",
    description: "New runtime and database diagnostics for hot-path profiling and query planning.",
    renderDashboard: () => createElement(RuntimePlanShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(RuntimePlanShowcase, { mode: "components" }),
  },
  {
    id: "theming",
    title: "AsciiTheme + color prop",
    description: "First-class theming with AsciiTheme provider, 4 built-in presets, custom overrides, nestable scoped themes, and per-component color prop.",
    renderDashboard: () => createElement(ThemingShowcase, { mode: "dashboard" }),
    renderComponents: () => createElement(ThemingShowcase, { mode: "components" }),
  },
] as const;
